### ISSUE TITLE
Scrape desktop telemetry probe stores

### ISSUE THREAD

**Issue by fbertsch** [mozilla/probe-scraper#110]
To support https://github.com/mozilla/probe-dictionary/issues/60, we need to add this info to the probe-info-service.

**Comment by fbertsch** [comment]
@badboy any interest in taking this on?

**Comment by badboy** [comment]
Interest sure, time currently is limited. I put it into the potential-list for the next week (or so), but no guarantees.

**Comment by fbertsch** [comment]
No problem, within the next 3-4 weeks would be great.
