### ISSUE TITLE
Scrape and publish Glean `pings.yaml`

### ISSUE THREAD

**Issue by fbertsch** [mozilla/probe-scraper#117]
This can be used in a few places:
- Mozilla-schema-generator, which currently does a backwards approach of needing all pings before it can get all probes, but it has to get the pings _from_ the probes
- bigquery-etl, to easily generate queries on every table (or view across them all)

This should scrape `pings.yaml`, and publish a history based on the pings present. I would imagine this lives in `/glean/$REPO/pings`.

**Comment by wlach** [comment]
@fbertsch I think this was implemented at some point? https://probeinfo.telemetry.mozilla.org/glean/fenix/pings seems to work

**Comment by wlach** [comment]
Closing this.
