### ISSUE TITLE
Save update time to general.json

### ISSUE THREAD

**Issue by georgf** [mozilla/probe-scraper#12]
While we save the update date to general.json as "lastUpdate", it would help to know at what time of day the update happened.
We could just change that to be a full ISO date string, including time and timezone info.

**Comment by DegCode** [comment]
Hi, I used dateutil package for time zone information and the result is this:

2017-09-03T23:44:25.825749+02:00

I’m from italy so timezone is UTC+2.

P.S.
I found this project and I would like to give some help, this is my first step in the open source world so advices will be gladly accepted.
If the format is acceptable I could send a Pull Request.

**Comment by georgf** [comment]
Hi, welcome!

This looks good, lets use that!

After we added this here, we can then later improve the frontend ([this project.(http://georgf.github.io/fx-data-explorer/)) to show the date in the users local timezone.

**Comment by georgf** [comment]
Fixed by #21.
