### ISSUE TITLE
Use a more robust firefox release date data source

### ISSUE THREAD

**Issue by Ben-Wu** [mozilla/probe-scraper#157]
In probe expiry alerts, we are currently scraping the firefox release calendar webpage for the release dates.  This isn't robust because if the html structure changes it will either fail or return incorrect data.  If there is a better alternate data source (e.g. json api), that should be used instead.

[Current code](https://github.com/mozilla/probe-scraper/blob/e99d2e4c50813d9b43929c57b6f564391cb49156/probe_scraper/scrapers/release_calendar.py)

Release dates are in this [google calendar](https://calendar.google.com/calendar/embed?src=bW96aWxsYS5jb21fZGJxODRhbnI5aTh0Y25taGFiYXRzdHY1Y29AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) but it also isn't an ideal source for the same reasons above.

**Comment by chutten** [comment]
As an alternative we could query buildhub (or, perhaps better yet, [the product-details service](https://product-details.mozilla.org/1.0/firefox_versions.json)) for the current latest version number. Then when that increases (like on Dec 3 when Nightly became 73) we could send a notice for probes that expire on latest + 1 (in this example, everything that expires in 74).

And this way we don't have to try and predict the future. We can say "Will expire in {latest + 1}" and send that email each week until "latest" increments and then we can say "Expired in {latest}".

What do you think? Versions are now 4 weeks apart, so warning people a version ahead of time wouldn't necessarily be an unreasonable thing to do.

**Comment by chutten** [comment]
Oh, another location that has the current version is https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/config/version.txt

(this is the file used to build Firefox, so is guaranteed to be up-to-date)

**Comment by Ben-Wu** [comment]
The product details service seems to be what I was looking for.  The "Expired in {latest}" behaviour would need to store the latest version as a state somehow right?  I don't know if that's possible with airflow.  Expiring in latest + 1 should work fine and I would prefer it over the release calendar scraping.

**Comment by chutten** [comment]
Nah, that's just for getting the tense right in the message text. `if probe_expiry_version <= latest_nightly_version: "Expired in {}.".format(latest_nightly_version) else: "Expires in {}".format(latest_nightly_version)`

**Comment by Ben-Wu** [comment]
Should we be alerting for all expired probes?  That seems a little spammy since it would be every week and include long forgotten probes.  Weekly alerts for expired in the latest and expiring in the next version would be my limit on how aggressive these alerts are.

**Comment by fbertsch** [comment]
I agree, no need to include all expired probes. Just send an email to the person about the probes that are relevant to them.

**Comment by chutten** [comment]
So that'd be a maximum of 8 alerts? (presuming 4-week releases) Sounds good to me.
