### ISSUE TITLE
Deliver JSON files gzip encoded

### ISSUE THREAD

**Issue by georgf** [mozilla/probe-scraper#17]
Loading performance is currently a pain point for the data explorer site.

The bulk of the wait is on probes.json, which is ~8MB and delivered uncompressed from the public S3 bucket.

I can think of two quick fixes here:
- gzip encode in the S3 bucket ([see bottom here](https://gist.github.com/georgf/0e6043c998c3bca754570a86d875d397), cuts my load times from 6s to 2s)
- publish them through a CloudFront distribution

@mreid-moz , does that sound right?
Any recommendations over either?
If CF, do i need to file a bug $somewhere to make it happen?

**Comment by mreid-moz** [comment]
Storing them gzipped (with the proper headers) in S3 sounds good to me. Nit: I think the content-type for json is normally `application/json`, and I'm not 100% sure about *not* adding the ".gz" extension to the file. I believe in the past I've used `.json.gz` or similar but it's been a while.

**Comment by georgf** [comment]
While we are here, we should also add `Cache-Control: max-age=...`, using say 6h or 8h.
