### ISSUE TITLE
Telemetry Probe Expiry emails are sent for probes that have been removed from the code

### ISSUE THREAD

**Issue by valenting** [mozilla/probe-scraper#171]
At the beginning of the 74 cycle we got an email about some expired/expiring probes:
```
The following probes are expiring in Firefox version 75:
NETWORK_CROSS_ORIGIN_STYLESHEET_CONTENT_TYPE


The following probes have expired in Firefox version 74:
NETWORK_CACHE_ISOLATION_ENTRY_COUNT_INCREASE
NETWORK_CACHE_ISOLATION_SIZE_INCREASE
NETWORK_CACHE_ISOLATION_UNIQUE_SITE_ACCESS_COUNT
```

These probes were removed in [bug 1607468](https://bugzil.la/1607468) and [bug 1606207](https://bugzil.la/1606207) but we are still getting emails about them every week or so. I believe this is a bug in the probe scraper.

**Comment by chutten** [comment]
Well that's certainly unintended. Paging @Ben-Wu

**Comment by Ben-Wu** [comment]
This is because the alerts are only based on what's in the probe info service output which contains removed probes.  It may be better to have the alerts look directly at the files in `toolkit/components/telemetry/` in the latest revision.
