### ISSUE TITLE
Separate Android metrics from platform-independent metrics in Glean repositories.yaml

### ISSUE THREAD

**Issue by mdboom** [mozilla/probe-scraper#185]
Currently the "glean" dependency as specified in the repositories.yaml includes metrics.yaml files both for Android and that apply to all platforms.

We should separate this out into two dependencies for Android and platform-independent, and the adjust all of the applications in the repositories.yaml to use the appropriate dependencies.

**Comment by fbertsch** [comment]
The plan is to have two libraries:
- `glean`, which will have just the core glean metrics
- `glean-android`, which will have the core glean metrics as well as the android-specific metrics

`glean` can be added to all non-Android apps, while `glean-android` replaces the existing `glean` library.

@mdboom @Dexterp37 which color should our bikeshed be, `glean` or `glean-core`?

**Comment by Dexterp37** [comment]
> 
> 
> The plan is to have two libraries:
> 
>     * `glean`, which will have just the core glean metrics
> 
>     * `glean-android`, which will have the core glean metrics as well as the android-specific metrics
> 
> 
> `glean` can be added to all non-Android apps, while `glean-android` replaces the existing `glean` library.
> 
> @mdboom @Dexterp37 which color should our bikeshed be, `glean` or `glean-core`?

I'd favour `glean-core` for consistency with our SDK naming :)

**Comment by fbertsch** [comment]
> I'd favour `glean-core` for consistency with our SDK naming :)

Sold!

The next question is about pings. Are the four default pings what we want for `glean-core`? Do those need to be split into separate files? (are non-mobile apps sending `baseline` pings, for example?) @Dexterp37

**Comment by Dexterp37** [comment]
> 
> 
> > I'd favour `glean-core` for consistency with our SDK naming :)
> 
> Sold!
> 
> The next question is about pings. Are the four default pings what we want for `glean-core`? Do those need to be split into separate files? (are non-mobile apps sending `baseline` pings, for example?) @Dexterp37

Yes, non-mobile apps can send `baseline` pings (at least with reason `dirty_startup`). There are no plans right now to split the pings in core vs non-core.

**Comment by fbertsch** [comment]
Fixed with https://github.com/mozilla/probe-scraper/pull/217.
