### ISSUE TITLE
For Firefox Desktop probes, include the name of the probe that we see in pings

### ISSUE THREAD

**Issue by robhudson** [mozilla/probe-scraper#195]
Why?

Downstream consumers have to perform complex string manipulation to convert something like `scalar/firstStartup.statusCode` to the name of the probe if searching in GLAM or BigQuery of `first_startup_status_code`.

There's a Python regex from Anthony in [this Github thread](https://github.com/mozilla/probe-dictionary/issues/89#issuecomment-618608820) that can be dropped in and a new property, perhaps `ping_name`, could be added to include this name for downstream consumers.

**Comment by robhudson** [comment]
If there's agreement that this is an appropriate place for this I can submit a pull request.

**Comment by tdsmith** [comment]
one related probe-dictionary issue: https://github.com/mozilla/probe-dictionary/issues/86

**Comment by robhudson** [comment]
We moved this downstream to probe-search. Closing here.

**Comment by fbertsch** [comment]
@robhudson can you link to the probe-search issue or PR?

**Comment by robhudson** [comment]
Relevant commit: https://github.com/mozilla/probe-search/commit/831288388d901d22d31a3c8b5a4057503d54a81e
