### ISSUE TITLE
Validate that repositories exist and yaml files are scrapable

### ISSUE THREAD

**Issue by wlach** [mozilla/probe-scraper#234]
At minimum our continuous integration should verify that all repositories listed in https://github.com/mozilla/probe-scraper/blob/master/repositories.yaml are reachable (from an unauthenticated session) and that the files contained therein are reachable. 

For the most part, we can probably do this validation with a simple python script using the requests library by hitting github endpoints (e.g. https://raw.githubusercontent.com/mozilla/mozregression/master/mozregression/metrics.yaml)

**Comment by edward-hong** [comment]
Sorry I'm not as experienced in Python as I am with Javascript and Svelte.
Can you please assign me a frontend task instead?

**Comment by LilyLME** [comment]
@wlach I would be happy to take this since @edward-hong does not want it.

**Comment by wlach** [comment]
> @wlach I would be happy to take this since @edward-hong does not want it.

Sure! This would be a good followup to what you were working on before.
