### ISSUE TITLE
ValueError: Errors processing Glean metrics

### ISSUE THREAD

**Issue by whd** [mozilla/probe-scraper#237]
```
 textPayload: "Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/probe_scraper/runner.py", line 450, in <module>
    main(args.cache_dir,
  File "/app/probe_scraper/runner.py", line 378, in main
    load_glean_metrics(cache_dir, out_dir, repositories_file, dry_run, glean_repo)
  File "/app/probe_scraper/runner.py", line 293, in load_glean_metrics
    raise ValueError("Errors processing Glean metrics")
ValueError: Errors processing Glean metrics
"  
```

[logs](https://console.cloud.google.com/logs/viewer?interval=CUSTOM&project=moz-fx-data-derived-datasets&minLogLevel=0&expandAll=false&timestamp=2020-09-18T04:56:50.549000000Z&customFacets=&limitCustomFacetWidth=true&scrollTimestamp=2020-09-18T02:01:24.276769490Z&dateRangeStart=2020-09-18T01:16:14.456Z&dateRangeEnd=2020-09-18T02:16:14.456Z&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22moz-fx-data-derived-datasets%22%0Aresource.labels.location%3D%22us-central1-a%22%0Aresource.labels.cluster_name%3D%22bq-load-gke-1%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.pod_name%3D%22probe-scraper-b40212e6%22)

**Comment by Dexterp37** [comment]
This was fixed in brizental/gleanjs@3a0bfd0b3b9f604ee41d548c72ca602841ec6170

**Comment by whd** [comment]
I'm going to leave this open until the probe-scraper DAG runs without error. When I re-ran the DAG today it [failed with the same error](https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=moz-fx-data-derived-datasets&minLogLevel=0&expandAll=false&timestamp=2020-09-18T19:21:51.767000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22moz-fx-data-derived-datasets%22%0Aresource.labels.location%3D%22us-central1-a%22%0Aresource.labels.cluster_name%3D%22bq-load-gke-1%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.pod_name%3D%22probe-scraper-55a630e4%22%0Aresource.labels.container_name%3D%22base%22&scrollTimestamp=2020-09-18T19:04:01.544567098Z), but there may be some hidden propagation issue that will be resolved by the next run (Sunday).

**Comment by fbertsch** [comment]
Okay, this is fixed by https://github.com/mozilla/probe-scraper/pull/240 and https://github.com/brizental/gleanjs/commit/e1e5ecc29905b8cfde3c234315c950d7a45be557
