### ISSUE TITLE
Add optional "prototype" property to applications and expose it in generated JSON

### ISSUE THREAD

**Issue by wlach** [mozilla/probe-scraper#244]
While working on the Glean Dictionary, we found that it might be helpful to have a "prototype" property to distinguish "applications" like GleanJs which are in development (and where we might expect to find e.g. non-existent data review).

@singhvaishnavi would you like to give this a try as a first bug? It's python/docker (not svelte). You can base work here off of the approach in #220. If you take it on, please add some tests to make sure things as working as expected while you're here.

@brizental has volunteered to mentor/review this.

**Comment by brizental** [comment]
Feel free to reach out to me on [Matrix](https://wiki.mozilla.org/Matrix) if necessary. My username there is also **brizental**.
