### ISSUE TITLE
"Telemetry Probe Expiry" emails sometimes don't include list of filed bugs

### ISSUE THREAD

**Issue by chutten** [mozilla/probe-scraper#253]
The Telemetry Probe Expiry email for Firefox 86 sent on Nov 18 had a list of bugs filed for the expiring probes... but the emails sent on Nov 25 and Dec 2 did not.

**Comment by fbertsch** [comment]
cc @Ben-Wu, if you have a chance to diagnose

**Comment by Ben-Wu** [comment]
I see what's happening here. The list of bugs only have bugs that were filed on that run of the script.  So if there aren't any new expiring probes this week, it will show the names of the bugs but won't file a bug and won't show a bug link.  This is unintuitive so I'll look into listing previously filed bugs.
