### ISSUE TITLE
Require channels be unique for applications

### ISSUE THREAD

**Issue by fbertsch** [mozilla/probe-scraper#275]
Downstream for probe-scraper we are going to generate a Looker view for every ping, and inside that view we will allow users to select channel. The problem right now is that channels are not unique; [Fenix has 5 channels](https://probeinfo.telemetry.mozilla.org/v2/glean/app-listings), 3 of which are nightly. We cannot parameterize based on channel when they are not unique.

To fix this, let's instead require that channel be unique, and mark the historic Fenix tables as deprecated. We can either:
1. De-list deprecated channels from probe-scraper, or
2. Let consumers decide how to handle deprecated channels (this requires them to understand that only non-deprecated channels are uniquely named)

**Comment by fbertsch** [comment]
cc @wlach, I'd like your input here on how this may affect the Glean Dictionary. How is it using the old Fenix nightly versions (`org.mozilla.fennec.aurora`, `org.mozilla.fenix.nightly`)?

**Comment by jklukas** [comment]
For Glean dictionary, I think it would be appropriate to ignore `org.mozilla.fennec.aurora` and `org.mozilla.fenix.nightly` completely.

> generate a Looker view for every ping, and inside that view we will allow users to select channel

Does this mean the view will know about multiple underlying tables and choose which one to query based on the channel value? Does Looker have some magic for handling the problem of unioning together tables with slightly different schemas?

**Comment by wlach** [comment]
This is kind of in flux, but the PR at mozilla/glean-dictionary#426 (which I'll merge after the next deploy when we add canonical app descriptions) describes the latest state of the art. Basically we do list all of the app ids per application, with metadata annotation:

![image](https://user-images.githubusercontent.com/20569/110014357-b2e0bc00-7cf0-11eb-8994-61673fb7e40f.png)

One piece that might be confusing is that we assume that where there are multiple app ids, there is a channel for each one.

I'd lean towards recommending (2).

**Comment by wlach** [comment]
> For Glean dictionary, I think it would be appropriate to ignore `org.mozilla.fennec.aurora` and `org.mozilla.fenix.nightly` completely.

We might be able to get away with that (since they were deprecated a while ago), but I think this problem will come up again. An application id / channel combination might still be needed to answer some questions (e.g. "how many people are on this deprecated version?") even after it is deprecated.

**Comment by fbertsch** [comment]
> Does this mean the view will know about multiple underlying tables and choose which one to query based on the channel value? Does Looker have some magic for handling the problem of unioning together tables with slightly different schemas?

The plan right now is to generate the LookML based on release. Looker has no need to do any unioning since it will generate queries on the underlying tables directly.

**Comment by fbertsch** [comment]
I've realized that dropping them from the output would also require dropping the associated tables in BQ, which is not the intended effect I want to have here. Let's stick with marking them as deprecated.
