### ISSUE TITLE
create bugs about expiring probes in toolkit/components/glean/metrics.yaml

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/probe-scraper#276]
In Firefox 89, the probes `fog_validation.legacy_telemetry_client_id/os_version/profile_disk_is_ssd` will expire. Unless they will be renewed or removed, this will cause build bustage. They are defined in [toolkit/components/glean/metrics.yaml](https://searchfox.org/mozilla-central/rev/44695ef057e422a8d6c6056972bdf32766c36187/toolkit/components/glean/metrics.yaml#52).

They should have been reported as expiring [similar to other telemetry probes](https://bugzilla.mozilla.org/buglist.cgi?list_id=15623791&query_format=advanced&email1=telemetry-probes%40mozilla.bugs&chfieldfrom=2021-02-21&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&chfield=%5BBug%20creation%5D&chfieldto=2021-03-08&emailtype1=substring&emailreporter1=1).

See [bug 1696890](https://bugzilla.mozilla.org/show_bug.cgi?id=1696890).

**Comment by chutten** [comment]
We also don't send emails. Which sets our users up to permafail their tests on merge day (a la https://bugzilla.mozilla.org/show_bug.cgi?id=1744667). We should both send emails _and_ file bugs.
