### ISSUE TITLE
MSG DAG failure: found incompatible changes

### ISSUE THREAD

**Issue by whd** [mozilla/probe-scraper#293]
/CC @acmiyaguchi @fbertsch 

[airflow run](https://workflow.telemetry.mozilla.org/log?task_id=mozilla_schema_generator&dag_id=probe_scraper&execution_date=2021-03-22T00%3A00%3A00%2B00%3A00)

**Comment by jklukas** [comment]
It looks like this is affecting all Glean custom pings, including all the pings pulled in from the sync library.
