### ISSUE TITLE
Missed probe removal

### ISSUE THREAD

**Issue by tdsmith** [mozilla/probe-scraper#40]
Hello! I'm not sure if this is the right place to document this, and it may be a dupe of #30, but:

- https://telemetry.mozilla.org/probe-dictionary/?detailView=histogram%2FDEVTOOLS_TOOLBOX_OPENED_BOOLEAN does not show that the probe was removed
- the probe was removed in https://hg.mozilla.org/mozilla-central/rev/668e08174667 as part of an effort to [convert BOOLEANs to COUNTs](https://bugzilla.mozilla.org/show_bug.cgi?id=1247985)

Please let me know if this isn't helpful. Thanks!

**Comment by georgf** [comment]
Hi @tdsmith, sorry for the delay and cheers for the clear report!

By your description, this is clearly a bug we need to fix and it's definitely in the right place.
I'll line this up for taking a look, but given our current load it might take a little to get here.

**Comment by georgf** [comment]
Looking at the [source data](https://probeinfo.telemetry.mozilla.org/firefox/all/main/all_probes), the output seems correct.
This looks like a front-end bug - checking into that.

**Comment by georgf** [comment]
I found the frontend issue, the fix is up for testing [here](https://github.com/mozilla/telemetry-dashboard/pull/543).
@tdsmith could you take a look and test the live link in the PR?
