### ISSUE TITLE
Add instructions for how to perform a dry-run for testing

### ISSUE THREAD

**Issue by chutten** [mozilla/probe-scraper#51]
As seen in #49, added tests may pass even though running against real data results in improper data.

It'd be nice to include in the README instructions for how to run the scraper quickly and locally.

As @fbertsch put it "just head to the probe-scraper repo and run: `python probe_scraper/runner.py`. If it's taking too long (it will), change `MIN_FIREFOX_VERSION` in `scrapers/moz_central_scraper.py` to e.g. `59` so it doesn't pull down as many files."

**Comment by fbertsch** [comment]
I'll take this when I get back from PTO, if it isn't done yet.
