### ISSUE TITLE
Deal with EOL Whitespace in outputted JSON

### ISSUE THREAD

**Issue by chutten** [mozilla/probe-scraper#52]
According to the [`json.dump` docs](https://docs.python.org/3.5/library/json.html#json.dump), the default `separators` value for Python 2 is `(', ', ': ')`, even with a non-default `indent` value.

This means before the `\n` at the end of lines with terminal commas there is a space. EOL Whitespace! Sound the alarm!

This was fixed in Python v3.4, but as the docs recommend and the current production job use `python` instead of `python3` this means we need to specify `separators=(',',': ')` in `json.dump`

**Comment by jhabarsingh** [comment]
@chutten can I work on this issue

**Comment by mdboom** [comment]
@jhabarsingh: I'm not @chutten, but sure!  I've assigned you to this issue.  Let us know if you have any issues with the implementation.

**Comment by jhabarsingh** [comment]
thanks @mdboom for assigning this issue to me.

**Comment by jhabarsingh** [comment]
I grepped the probe-scraper 
```
grep -r  'json.dump'

```
```
./probe_scraper/scrapers/moz_central_scraper.py:        json.dump(error_cache, f, sort_keys=True, indent=2)
./probe_scraper/runner.py:        json.dump(data, f, sort_keys=True, indent=2)

```
I found json.dump is being used at two places. should I add the separators

**Comment by mdboom** [comment]
Yes.  Sounds like a good place to start.

**Comment by jhabarsingh** [comment]
Sir when I am running `make test` command, I am getting this
```
================================================================== warnings summary ==================================================================
/usr/local/lib/python3.8/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py:1
/usr/local/lib/python3.8/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py:1
  /usr/local/lib/python3.8/site-packages/botocore/vendored/requests/packages/urllib3/_collections.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import Mapping, MutableMapping

tests/test_git_scraper.py::test_normal_repo
tests/test_git_scraper.py::test_improper_metrics_repo
tests/test_git_scraper.py::test_check_for_duplicate_metrics
tests/test_git_scraper.py::test_check_for_expired_metrics
tests/test_repositories_parser.py::test_repositories
tests/test_repositories_parser.py::test_repositories_parser_incorrect
tests/test_repositories_parser.py::test_repositories_parser_not_kebab_case
tests/test_repositories_parser.py::test_repositories_class
  /usr/local/lib/python3.8/site-packages/jsonschema/validators.py:928: DeprecationWarning: The metaschema specified by $schema was not found. Using the latest draft to validate, but this will raise an error in the future.
    cls = validator_for(schema)

tests/test_histogram_parser.py::test_histogram_parser_old
tests/test_histogram_parser.py::test_histogram_parser_new
  /app/probe_scraper/parsers/third_party/usecounters.py:11: DeprecationWarning: 'U' mode is deprecated
    stream = open(conf_filename, 'rU')

-- Docs: https://docs.pytest.org/en/stable/warnings.html
==================================================== 53 passed, 12 warnings in 218.96s (0:03:38) =====================================================
```

Even though I didn't made any changes in the forked repository, I am getting 12 warnings.

**Comment by mdboom** [comment]
@jhabarsingh : These warnings look mostly harmless to me. I think they are mostly related to versions of Python and other dependencies changing since this code was originally written. I don't think we need to fix them as part of your current work (we can merge it without fixing these warnings, assuming @fbertsch agrees).  However, it would be great to track them and fix them.  If you are interested in continuing to help, it would be much appreciated if you wanted to make new issues for each of these warnings and then we can tackle fixing them one-by-one.

**Comment by jhabarsingh** [comment]
yeah sure I will try to resolve these.

**Comment by jhabarsingh** [comment]
@mdboom, I sent a PR  for issue #207 can you please review it.

**Comment by jhabarsingh** [comment]
diff --git a/probe_scraper/runner.py b/probe_scraper/runner.py
index e9cb582..95535e2 100644
--- a/probe_scraper/runner.py
+++ b/probe_scraper/runner.py
@@ -70,7 +70,7 @@ def dump_json(data, out_dir, file_name):
     path = os.path.join(out_dir, file_name)
     with open(path, 'w') as f:
         print("  " + path)
-        json.dump(data, f, sort_keys=True, indent=2)
+        json.dump(data, f, sort_keys=True, indent=2, separators=(',',': '))
 
 
 def write_moz_central_probe_data(probe_data, revisions, out_dir):
diff --git a/probe_scraper/scrapers/moz_central_scraper.py b/probe_scraper/scrapers/moz_central_scraper.py
index eba9fd9..c2aa20c 100644
--- a/probe_scraper/scrapers/moz_central_scraper.py
+++ b/probe_scraper/scrapers/moz_central_scraper.py
@@ -244,7 +244,7 @@ def load_error_cache(folder):
 def save_error_cache(folder, error_cache):
     path = os.path.join(folder, ERROR_CACHE_FILENAME)
     with open(path, 'w') as f:
-        json.dump(error_cache, f, sort_keys=True, indent=2)
+        json.dump(error_cache, f, sort_keys=True, indent=2, separators=(',',': '))
 
 
 def scrape(folder=None, min_fx_version=None, max_fx_version=None, channels=None):

**Comment by jhabarsingh** [comment]
@mdboom , I am able to run  tests and lints successfully.

**Comment by jhabarsingh** [comment]
sorry sir by mistake i closed the branch
