### ISSUE TITLE
Firefox-ios: update files so that glean-probe-scraper.yml works after major changes in repo 

### ISSUE THREAD

**Issue by isabelrios** [mozilla/probe-scraper#666]
Similar to issue #659, we will be moving all Firefox-ios application files into a firefox-ios folder.
https://github.com/mozilla/probe-scraper/issues/659#issuecomment-1819493390
The files mentioned in this comment will be moved to:
firefox-ios/Clienti/metrics.yaml, firefox-ios/Storage/metrics.yaml, firefox-ios/Client/pings.yaml and firefox-ios/Client/tags.yaml

The [PR](https://github.com/mozilla-mobile/firefox-ios/pull/17460) is still WIP, but wanted to have this issue open for you to know and so that we don't miss these changes.

Thanks!

**Comment by isabelrios** [comment]
FYi, the PR that would need this change has just landed on firefox-ios repo. Thanks!

**Comment by isabelrios** [comment]
cc @relud @Dexterp37

**Comment by badboy** [comment]
I'm taking this.

**Comment by isabelrios** [comment]
The github action in firefox-ios, https://github.com/mozilla-mobile/firefox-ios/actions/runs/7301808341/job/19899214190

```
curl: 
(22) The requested URL returned error: 400
Error: Client/metrics.yaml not found in commit 0a104d00ca111300584bd8d271750fec7030b89a for org-mozilla-ios-firefox
Error: Process completed with exit code 22. is still failing... 
```

@badboy  I'm not sure if that's something we need to change somewhere in our code or it should be fixed here...

**Comment by badboy** [comment]
Seems this all green now.

**Comment by isabelrios** [comment]
> Seems this all green now.

Yes! thanks!
