### ISSUE TITLE
Add `delete_after_days` for the user-charecteristics ping

### ISSUE THREAD

**Issue by tomrittervg** [mozilla/probe-scraper#759]
The [user characteristics ping](https://searchfox.org/mozilla-central/source/toolkit/components/resistfingerprinting/pings.yaml#8-21) is supposed to have an extra-limited retention window of 90 days (and in the future we might try to trim that to 30) - but I don't know if this is codified in the repositories.yaml file correctly.
```[tasklist]
### Tasks
```

**Comment by mozfreddyb** [comment]
@sean-rose @whd Can you help me find out how to make progress on this? It's important that we do not retain the data for longer than planned.

**Comment by sean-rose** [comment]
@mozfreddyb you'll need to define an expiration policy for the `user-characteristics` ping in `repositories.yaml`, like [is done for some other pings](https://github.com/mozilla/probe-scraper/blob/861bae16adcdb356100d07c457a0f29118a5ca49/repositories.yaml#L340-L360).
