### ISSUE TITLE
Use buildhub2 instead of buildhub (soon to be deprecated)

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/probe-scraper#89]
From an email sent to the Stability list (thanks @chutten ), turns out that buildhub will be deprecated on July and that we should move to [buildhub2](https://buildhub2.readthedocs.io/en/latest/user.html), before then.

@fbertsch did you already know about this?

**Comment by fbertsch** [comment]
We use the buildhub2 url: https://github.com/mozilla/probe-scraper/blob/master/probe_scraper/scrapers/buildhub.py#L13

Looks like that URL is staying the same so we are good to go!
