### ISSUE TITLE
Add a schema for repositories.yaml

### ISSUE THREAD

**Issue by fbertsch** [mozilla/probe-scraper#93]
It's easy to make small, not noticeable mistakes. A schema that validates would not allow this.

**Comment by fbertsch** [comment]
@mdboom any interest in taking this on?

**Comment by mdboom** [comment]
I *think* there already is one, it's just not being validated against at runtime?

https://github.com/mozilla/probe-scraper/blob/master/schemas/repositories.json

**Comment by fbertsch** [comment]
Oh, wow, you're definitely right. [It's being run here.](https://github.com/mozilla/probe-scraper/blob/master/probe_scraper/parsers/repositories.py#L58)

It looks like we need to tighten the screws a bit and set `additionalProperties=False`.

**Comment by fbertsch** [comment]
Note: [It does run during testing as well.](https://github.com/mozilla/probe-scraper/blob/master/tests/test_repositories_parser.py#L49)

**Comment by mdboom** [comment]
Ok, cool.  So I'll take on tightening the screws and adding some additional tests, etc...
