### ISSUE TITLE
Add dependencies for reference browser

### ISSUE THREAD

**Issue by fbertsch** [mozilla/probe-scraper#96]
The reference browser integrated lib-crash, but the probe-scraper doesn't know about it, so the BQ schema doesn't have those metrics. We need to make a scrapable dependencies file (ala Fenix) and add it here.

If that's too much work, we could consider manually stating the dependencies (for a short-term solution - or it could be long-term if we realize we're not going to be adding many dependencies in the future).

cc @mdboom @travis79

**Comment by mdboom** [comment]
For reference, here's how this was done in Fenix: https://github.com/mozilla-mobile/fenix/pull/1996

I don't even know what &browser is doing for CI and how applicable that is, but I'll spend some time poking around...

**Comment by Dexterp37** [comment]
I wish we really, really, REALLY didn't have to impose this requirement on the application itself. Almost OT: do we have a document for "things you need to do *after* adding the Glean SDK to your project?"

**Comment by mdboom** [comment]
We have Glean/probe-scraper docs here: https://github.com/mozilla/probe-scraper#adding-a-new-glean-repository

**Comment by Dexterp37** [comment]
> 
> 
> We have Glean/probe-scraper docs here: https://github.com/mozilla/probe-scraper#adding-a-new-glean-repository

Do we need to link this [here](https://docs.telemetry.mozilla.org/concepts/glean/glean.html#how-to-use-glean) or would that happen as part of the "bug for engineering to allow for the application id"? Maybe that's a @fbertsch question

**Comment by fbertsch** [comment]
Completed.
